# Generated by Django 2.2.1 on 2019-07-01 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import pkfrance.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=200)),
                ('description', markdownx.models.MarkdownxField()),
                ('in_game', models.TextField()),
                ('image1', pkfrance.fields.ResizeImageField(size=[700, 400], upload_to='dinosaur')),
                ('image2', pkfrance.fields.ResizeImageField(size=[700, 400], upload_to='dinosaur')),
                ('image3', pkfrance.fields.ResizeImageField(size=[700, 400], upload_to='dinosaur')),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('image', pkfrance.fields.ResizeImageField(size=[350, 200], upload_to='fact')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField(max_length=550)),
                ('body', markdownx.models.MarkdownxField()),
                ('date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('image', pkfrance.fields.ResizeImageField(size=[700, 400], upload_to='article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
