# Generated by Django 2.2.1 on 2019-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='new',
            name='image',
        ),
        migrations.AddField(
            model_name='new',
            name='url_image',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
