# Generated by Django 2.2.1 on 2019-05-31 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190531_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='sum',
            new_name='summary',
        ),
    ]
