# Generated by Django 2.2.1 on 2019-05-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190531_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Article',
        ),
    ]
