# Generated by Django 2.2.1 on 2019-05-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190531_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_image',
            field=models.CharField(max_length=250),
        ),
    ]
