# Generated by Django 2.2.1 on 2019-06-03 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20190531_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='url_image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='http://placehold.it/700x400', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('image1', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
