# Generated by Django 2.2.1 on 2019-06-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190603_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='image1',
            new_name='image',
        ),
    ]
