# Generated by Django 2.2.1 on 2019-06-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190603_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='image',
            field=models.ImageField(height_field='150', upload_to='', width_field='250'),
        ),
    ]
